// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

package dto;

public final class UserProtoDTO {
    private UserProtoDTO() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface UserDTOOrBuilder extends
            // @@protoc_insertion_point(interface_extends:data.UserDTO)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 id = 1;</code>
         * @return Whether the id field is set.
         */
        boolean hasId();
        /**
         * <code>required int32 id = 1;</code>
         * @return The id.
         */
        int getId();

        /**
         * <code>required string name = 2;</code>
         * @return Whether the name field is set.
         */
        boolean hasName();
        /**
         * <code>required string name = 2;</code>
         * @return The name.
         */
        java.lang.String getName();
        /**
         * <code>required string name = 2;</code>
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>required string surname = 3;</code>
         * @return Whether the surname field is set.
         */
        boolean hasSurname();
        /**
         * <code>required string surname = 3;</code>
         * @return The surname.
         */
        java.lang.String getSurname();
        /**
         * <code>required string surname = 3;</code>
         * @return The bytes for surname.
         */
        com.google.protobuf.ByteString
        getSurnameBytes();

        /**
         * <code>repeated string languages = 4;</code>
         * @return A list containing the languages.
         */
        java.util.List<java.lang.String>
        getLanguagesList();
        /**
         * <code>repeated string languages = 4;</code>
         * @return The count of languages.
         */
        int getLanguagesCount();
        /**
         * <code>repeated string languages = 4;</code>
         * @param index The index of the element to return.
         * @return The languages at the given index.
         */
        java.lang.String getLanguages(int index);
        /**
         * <code>repeated string languages = 4;</code>
         * @param index The index of the value to return.
         * @return The bytes of the languages at the given index.
         */
        com.google.protobuf.ByteString
        getLanguagesBytes(int index);
    }
    /**
     * Protobuf type {@code data.UserDTO}
     */
    public static final class UserDTO extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:data.UserDTO)
            UserDTOOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use UserDTO.newBuilder() to construct.
        private UserDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private UserDTO() {
            name_ = "";
            surname_ = "";
            languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new UserDTO();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private UserDTO(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            name_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            surname_ = bs;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                                languages_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            languages_.add(bs);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000008) != 0)) {
                    languages_ = languages_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dto.UserProtoDTO.internal_static_data_UserDTO_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dto.UserProtoDTO.internal_static_data_UserDTO_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dto.UserProtoDTO.UserDTO.class, dto.UserProtoDTO.UserDTO.Builder.class);
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private int id_;
        /**
         * <code>required int32 id = 1;</code>
         * @return Whether the id field is set.
         */
        @java.lang.Override
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;
        /**
         * <code>required string name = 2;</code>
         * @return Whether the name field is set.
         */
        @java.lang.Override
        public boolean hasName() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required string name = 2;</code>
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string name = 2;</code>
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SURNAME_FIELD_NUMBER = 3;
        private volatile java.lang.Object surname_;
        /**
         * <code>required string surname = 3;</code>
         * @return Whether the surname field is set.
         */
        @java.lang.Override
        public boolean hasSurname() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required string surname = 3;</code>
         * @return The surname.
         */
        @java.lang.Override
        public java.lang.String getSurname() {
            java.lang.Object ref = surname_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    surname_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string surname = 3;</code>
         * @return The bytes for surname.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSurnameBytes() {
            java.lang.Object ref = surname_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                surname_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LANGUAGES_FIELD_NUMBER = 4;
        private com.google.protobuf.LazyStringList languages_;
        /**
         * <code>repeated string languages = 4;</code>
         * @return A list containing the languages.
         */
        public com.google.protobuf.ProtocolStringList
        getLanguagesList() {
            return languages_;
        }
        /**
         * <code>repeated string languages = 4;</code>
         * @return The count of languages.
         */
        public int getLanguagesCount() {
            return languages_.size();
        }
        /**
         * <code>repeated string languages = 4;</code>
         * @param index The index of the element to return.
         * @return The languages at the given index.
         */
        public java.lang.String getLanguages(int index) {
            return languages_.get(index);
        }
        /**
         * <code>repeated string languages = 4;</code>
         * @param index The index of the value to return.
         * @return The bytes of the languages at the given index.
         */
        public com.google.protobuf.ByteString
        getLanguagesBytes(int index) {
            return languages_.getByteString(index);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSurname()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeInt32(1, id_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, surname_);
            }
            for (int i = 0; i < languages_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, languages_.getRaw(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, surname_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < languages_.size(); i++) {
                    dataSize += computeStringSizeNoTag(languages_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getLanguagesList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof dto.UserProtoDTO.UserDTO)) {
                return super.equals(obj);
            }
            dto.UserProtoDTO.UserDTO other = (dto.UserProtoDTO.UserDTO) obj;

            if (hasId() != other.hasId()) return false;
            if (hasId()) {
                if (getId()
                        != other.getId()) return false;
            }
            if (hasName() != other.hasName()) return false;
            if (hasName()) {
                if (!getName()
                        .equals(other.getName())) return false;
            }
            if (hasSurname() != other.hasSurname()) return false;
            if (hasSurname()) {
                if (!getSurname()
                        .equals(other.getSurname())) return false;
            }
            if (!getLanguagesList()
                    .equals(other.getLanguagesList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasId()) {
                hash = (37 * hash) + ID_FIELD_NUMBER;
                hash = (53 * hash) + getId();
            }
            if (hasName()) {
                hash = (37 * hash) + NAME_FIELD_NUMBER;
                hash = (53 * hash) + getName().hashCode();
            }
            if (hasSurname()) {
                hash = (37 * hash) + SURNAME_FIELD_NUMBER;
                hash = (53 * hash) + getSurname().hashCode();
            }
            if (getLanguagesCount() > 0) {
                hash = (37 * hash) + LANGUAGES_FIELD_NUMBER;
                hash = (53 * hash) + getLanguagesList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dto.UserProtoDTO.UserDTO parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static dto.UserProtoDTO.UserDTO parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static dto.UserProtoDTO.UserDTO parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static dto.UserProtoDTO.UserDTO parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(dto.UserProtoDTO.UserDTO prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code data.UserDTO}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:data.UserDTO)
                dto.UserProtoDTO.UserDTOOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dto.UserProtoDTO.internal_static_data_UserDTO_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dto.UserProtoDTO.internal_static_data_UserDTO_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dto.UserProtoDTO.UserDTO.class, dto.UserProtoDTO.UserDTO.Builder.class);
            }

            // Construct using dto.UserProtoDTO.UserDTO.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                surname_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dto.UserProtoDTO.internal_static_data_UserDTO_descriptor;
            }

            @java.lang.Override
            public dto.UserProtoDTO.UserDTO getDefaultInstanceForType() {
                return dto.UserProtoDTO.UserDTO.getDefaultInstance();
            }

            @java.lang.Override
            public dto.UserProtoDTO.UserDTO build() {
                dto.UserProtoDTO.UserDTO result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dto.UserProtoDTO.UserDTO buildPartial() {
                dto.UserProtoDTO.UserDTO result = new dto.UserProtoDTO.UserDTO(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.id_ = id_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.surname_ = surname_;
                if (((bitField0_ & 0x00000008) != 0)) {
                    languages_ = languages_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                result.languages_ = languages_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dto.UserProtoDTO.UserDTO) {
                    return mergeFrom((dto.UserProtoDTO.UserDTO)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dto.UserProtoDTO.UserDTO other) {
                if (other == dto.UserProtoDTO.UserDTO.getDefaultInstance()) return this;
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasName()) {
                    bitField0_ |= 0x00000002;
                    name_ = other.name_;
                    onChanged();
                }
                if (other.hasSurname()) {
                    bitField0_ |= 0x00000004;
                    surname_ = other.surname_;
                    onChanged();
                }
                if (!other.languages_.isEmpty()) {
                    if (languages_.isEmpty()) {
                        languages_ = other.languages_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                    } else {
                        ensureLanguagesIsMutable();
                        languages_.addAll(other.languages_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasId()) {
                    return false;
                }
                if (!hasName()) {
                    return false;
                }
                if (!hasSurname()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                dto.UserProtoDTO.UserDTO parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (dto.UserProtoDTO.UserDTO) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int id_ ;
            /**
             * <code>required int32 id = 1;</code>
             * @return Whether the id field is set.
             */
            @java.lang.Override
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>required int32 id = 1;</code>
             * @return The id.
             */
            @java.lang.Override
            public int getId() {
                return id_;
            }
            /**
             * <code>required int32 id = 1;</code>
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(int value) {
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int32 id = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";
            /**
             * <code>required string name = 2;</code>
             * @return Whether the name field is set.
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000002) != 0);
            }
            /**
             * <code>required string name = 2;</code>
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string name = 2;</code>
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string name = 2;</code>
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string name = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>required string name = 2;</code>
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object surname_ = "";
            /**
             * <code>required string surname = 3;</code>
             * @return Whether the surname field is set.
             */
            public boolean hasSurname() {
                return ((bitField0_ & 0x00000004) != 0);
            }
            /**
             * <code>required string surname = 3;</code>
             * @return The surname.
             */
            public java.lang.String getSurname() {
                java.lang.Object ref = surname_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        surname_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string surname = 3;</code>
             * @return The bytes for surname.
             */
            public com.google.protobuf.ByteString
            getSurnameBytes() {
                java.lang.Object ref = surname_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    surname_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string surname = 3;</code>
             * @param value The surname to set.
             * @return This builder for chaining.
             */
            public Builder setSurname(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                surname_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string surname = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearSurname() {
                bitField0_ = (bitField0_ & ~0x00000004);
                surname_ = getDefaultInstance().getSurname();
                onChanged();
                return this;
            }
            /**
             * <code>required string surname = 3;</code>
             * @param value The bytes for surname to set.
             * @return This builder for chaining.
             */
            public Builder setSurnameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                surname_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.LazyStringList languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private void ensureLanguagesIsMutable() {
                if (!((bitField0_ & 0x00000008) != 0)) {
                    languages_ = new com.google.protobuf.LazyStringArrayList(languages_);
                    bitField0_ |= 0x00000008;
                }
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @return A list containing the languages.
             */
            public com.google.protobuf.ProtocolStringList
            getLanguagesList() {
                return languages_.getUnmodifiableView();
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @return The count of languages.
             */
            public int getLanguagesCount() {
                return languages_.size();
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @param index The index of the element to return.
             * @return The languages at the given index.
             */
            public java.lang.String getLanguages(int index) {
                return languages_.get(index);
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @param index The index of the value to return.
             * @return The bytes of the languages at the given index.
             */
            public com.google.protobuf.ByteString
            getLanguagesBytes(int index) {
                return languages_.getByteString(index);
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @param index The index to set the value at.
             * @param value The languages to set.
             * @return This builder for chaining.
             */
            public Builder setLanguages(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLanguagesIsMutable();
                languages_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @param value The languages to add.
             * @return This builder for chaining.
             */
            public Builder addLanguages(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLanguagesIsMutable();
                languages_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @param values The languages to add.
             * @return This builder for chaining.
             */
            public Builder addAllLanguages(
                    java.lang.Iterable<java.lang.String> values) {
                ensureLanguagesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, languages_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearLanguages() {
                languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string languages = 4;</code>
             * @param value The bytes of the languages to add.
             * @return This builder for chaining.
             */
            public Builder addLanguagesBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLanguagesIsMutable();
                languages_.add(value);
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:data.UserDTO)
        }

        // @@protoc_insertion_point(class_scope:data.UserDTO)
        private static final dto.UserProtoDTO.UserDTO DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new dto.UserProtoDTO.UserDTO();
        }

        public static dto.UserProtoDTO.UserDTO getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<UserDTO>
                PARSER = new com.google.protobuf.AbstractParser<UserDTO>() {
            @java.lang.Override
            public UserDTO parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UserDTO(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<UserDTO> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<UserDTO> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dto.UserProtoDTO.UserDTO getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_data_UserDTO_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_data_UserDTO_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\010my.proto\022\004data\"G\n\007UserDTO\022\n\n\002id\030\001 \002(\005\022" +
                        "\014\n\004name\030\002 \002(\t\022\017\n\007surname\030\003 \002(\t\022\021\n\tlangua" +
                        "ges\030\004 \003(\tB\024\n\004dataB\014UserProtoDTO"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_data_UserDTO_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_data_UserDTO_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_data_UserDTO_descriptor,
                new java.lang.String[] { "Id", "Name", "Surname", "Languages", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
